server:
  port: 8000
#  context-path: /dataplatform


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.200:3306/microservice?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itmuch.cloud.pojo
  type-handlers-package: com.itmuch.cloud.typehandler
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    local-cache-scope: statement

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSqla

logging:
  level:
    root: INFO
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
